### ISSUE TITLE
Building with Webpack: getting fs error

### ISSUE THREAD

**Issue by pierreis** [sdawood/dynamo-update-expression#1]
I got an error when compacting this module with Webpack (for use on an AWS Lambda application).

```js
[ 'Error: EBADF: bad file descriptor, fstat',
  'at tryStatSync (fs.js:534:13)',
  'at Object.fs.readFileSync (fs.js:570:3)',
  'at Object._ast.initialize._nodes (...)'
```

It seems that the grammar modules used are trying to read from the disk, which obviously fails. I'm not sure why this module requires reading from the disk in the first place.
Is there a way to fix this behavior?

**Comment by sdawood** [comment]
Hello @pierreis, did you manage to overcome the webpack issue? Otherwise please share your build pipeline to reproduce the error.

**Comment by juvaly** [comment]
This seems to be a problem with the JsonPath package. 
See here https://github.com/dchester/jsonpath/issues/50

Consider switching to this fork, which includes a fix https://github.com/ooxi/jsonpath

**Comment by pierreis** [comment]
@juvaly It is, your solution fixed the problem. Thanks!
